# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
   #api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9e0776597ef67194155df40591a532d5941b4386a5d217cb11334162b28f8e4735cd5634b76555edd1a2fad19485443b62dfe81a8a0b1fd6b11a9f1804324299

test:
  secret_key_base: 773f8d6b9729f38c0e9d1a53f1a5474a5b782016c2b1a271b1e7f415d156db3f1bdbb6dfd8fa93a62871e46d5a9395ebd16f719047fc02296c9effab9fbff70d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
